name: Actions Updates

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      run: python test_actions/task.py

    - name: Create Pull Request
      id: create_pull_request
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # pin @v6.1.0
      with:
        committer: ''
        branch: update-timestamp
        commit-message: 'update timestamp'
        title: '[Actions Workflow] update timestamp'
        body: 'by GitHub Actions'
        labels: 'auto-update'
        base: main